CREATE TABLE 教室 (
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 名前 VARCHAR(20) UNIQUE
);
INSERT INTO 教室 (名前) VALUES ('実習室1');
INSERT INTO 教室 (名前) VALUES ('実習室2');
INSERT INTO 教室 (名前) VALUES ('実習室3');
INSERT INTO 教室 (名前) VALUES ('LL教室');
SELECT * FROM 教室;