CREATE TABLE 学生(
 学籍番号 INTEGER PRIMARY KEY AUTOINCREMENT,
 氏名 VARCHAR(100) NOT NULL,
 学部ID INTEGER REFERENCES 学部(ID) NOT NULL 
);
INSERT INTO 学生(氏名,学部ID) VALUES ('渋沢栄一',1);
INSERT INTO 学生(氏名,学部ID) VALUES ('野口英世',2);